name: $NAME
description: $DESCRIPTION
version: 0.1.0
scripts:
  - start: "python ./main.py"
  - test: "echo Not implemented"
author: $AUTHOR
license: $LICENSE
dependencies:
  - python:
      version: ">=3.9.0"
